### ISSUE TITLE
:))

### ISSUE THREAD

**Issue by deoxxa** [binhnguyennus/awesome-scalability#1]
You came into a slack channel and dumped your link to this repository without reading the topic of the channel. This shows that you are lazy and you have no respect for the people who are there. I hope you have a bad day.

![image](https://user-images.githubusercontent.com/479055/35249313-9f0ba3de-0025-11e8-87cd-822974f636f9.png)

**Comment by frezbo** [comment]
Well I appreciate the effort taken into compiling a huge list of resources, it would be nice to limit yourselves in multiple slack channels. Good day.

**Comment by binhnguyennus** [comment]
Close issue

**Comment by binhnguyennus** [comment]
@deoxxa  and @JonRowe, please act like men, if you are :))

**Comment by deoxxa** [comment]
Wait, did you just come back two weeks later to say that? lol.

**Comment by binhnguyennus** [comment]
@deoxxa Not really, just wanna check how quick you will react if I call you :)) Actually, quicker than my puppy 👍
