### ISSUE TITLE
Shared-State Concurrency - error 404

### ISSUE THREAD

**Issue by fuelen** [binhnguyennus/awesome-scalability#18]
Any other source of this?

**Comment by binhnguyennus** [comment]
Hi @fuelen , thanks a lot for notifying me :) I am not sure why the old link was broken. I have replaced it with a new one. Actually, you can find Shared-State Concurrency in most of Operating System textbook. Btw taking a look of how it is implemented in a 'real' language (Rust) is not a bad idea.

Have a nice day!
/Binh.

**Comment by fuelen** [comment]
Thanks!
