### ISSUE TITLE
Top 5 Scalability Patterns

### ISSUE THREAD

**Issue by sohaibfarooqi** [binhnguyennus/awesome-scalability#28]
I recently came across this article [Top 5 scalability patterns](https://www.f5.com/company/blog/top-five-scalability-patterns) I have searched the current list of links and I am unable to find it. Do you think we should add this?

Regards,
Sohaib

**Comment by binhnguyennus** [comment]
@sohaibfarooqi Cool! I have added it! Thanks a lot :+1:
