### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by Calinou** [binhnguyennus/awesome-scalability#3]
A license should be added to this repository, see the [recommendations from `sindresorhus/awesome`](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license). I would personally recommend CC0 for this.

**Comment by binhnguyennus** [comment]
Thank you very much for your suggestion! I have added recently. Please take a look and let me know if it was ok :)

**Comment by Calinou** [comment]
Looks good to me. :+1:
