### ISSUE TITLE
Bigflow (potential successor of Spark) 

### ISSUE THREAD

**Issue by LifeIsStrange** [binhnguyennus/awesome-scalability#4]
https://github.com/baidu/bigflow

**Comment by binhnguyennus** [comment]
Thank you very much for your introduction of BigFlow 👍 But it would be great if you can send me a link of an English article :clinking_glasses:

**Comment by LifeIsStrange** [comment]
I can't yet find an english description on the Web because bigflow is really new.
The only thing I got is the intro 
"
Baidu Bigflow is an interface that allows for writing distributed computing programs and provides lots of simple, flexible, powerful APIs. Using Bigflow, you can easily handle data of any scale. Bigflow processes 4P+ data inside Baidu and runs about 5000 jobs every day.
"
But it's potentially the next Big Thing, and Baidu is the chinese Google.

Solutions : Wait for this to be resolved :

https://github.com/baidu/bigflow/issues/29
Maybe we could accelerate it by suggesting a crowdin, https://crowdin.com/

Meanwhile you could link the bigflow readme with a Google translate link or a deepl.io, it's still better than not showing it to the people interested in state of the art Scalability.

**Comment by binhnguyennus** [comment]
@LifeIsStrange  Sorry for my late reply! I was spending much time to find a good English article for Bigflow in the last two week. However, I still was not be able to get it done with a commit. By the way, I added several good articles in Distributed Machine Learning from Baidu Research Blog. Could you please take a look! 谢谢你 !
